### ISSUE TITLE
build/iOS/Debug/src/Fuse.Stripe.Card.mm:6:10: 'STPCardBrand.h' file not found

### ISSUE THREAD

**Issue by fredfalcon** [fuse-compound/Fuse.Stripe#2]
Getting this error when building for iOS.  

Seems to work ok on Android though.

**Comment by fredfalcon** [comment]
so running this command seemed to include the header file - uno build --target=iOS --configuration=Release -adebug -DCocoaPods -r

Now there seems to be another issue.  When I start the project, it's getting frozen on the payment page..  The project is here by the way - https://github.com/Emrals/Fuse

**Comment by fredfalcon** [comment]
Figured it out!  I had an error with some stale code on the payment page.  Seems to be working ok now.    I think my issue was I was not including the -DCocoaPods flag.

**Comment by cbaggers** [comment]
Thanks for coming back to write up your findings, its a big help.
